export const API_DOCS = {
  success: true,
  message: "AuthFlow API Documentation",
  version: "1.0.0",
  endpoints: {
    auth: {
      register: "POST /api/auth/register",
      login: "POST /api/auth/login",
      logout: "POST /api/auth/logout",
      refreshToken: "POST /api/auth/refresh-token",
      verifyEmail: "POST /api/auth/verify-email",
      requestPasswordReset: "POST /api/auth/request-password-reset",
      resetPassword: "POST /api/auth/reset-password",
      getCurrentUser: "GET /api/auth/me",
      getSessions: "GET /api/auth/sessions",
      revokeSession: "DELETE /api/auth/sessions/:sessionId",
    },
    oauth: {
      google: "GET /api/auth/google",
      googleCallback: "GET /api/auth/google/callback",
      github: "GET /api/auth/github",
      githubCallback: "GET /api/auth/github/callback",
      magicLink: "POST /api/auth/magic-link",
      verifyMagicLink: "POST /api/auth/magic-link/verify",
    },
    mfa: {
      setup: "POST /api/mfa/setup",
      verify: "POST /api/mfa/verify",
      activate: "POST /api/mfa/activate",
      validate: "POST /api/mfa/validate",
      disable: "POST /api/mfa/disable",
      backupCodes: "POST /api/mfa/backup-codes",
    },
    apiKeys: {
      list: "GET /api/api-keys",
      create: "POST /api/api-keys",
      get: "GET /api/api-keys/:id",
      delete: "DELETE /api/api-keys/:id",
    },
    applications: {
      list: "GET /api/applications",
      create: "POST /api/applications",
      get: "GET /api/applications/:id",
      update: "PATCH /api/applications/:id",
      rotateSecret: "POST /api/applications/:id/rotate-secret",
      delete: "DELETE /api/applications/:id",
    },
    sdk: {
      register: "POST /api/sdk/auth/register",
      login: "POST /api/sdk/auth/login",
      me: "GET /api/sdk/auth/me",
      refresh: "POST /api/sdk/auth/refresh",
      logout: "POST /api/sdk/auth/logout",
      verifyToken: "GET /api/sdk/token/verify",
    },
    organizations: {
      list: "GET /api/organizations/my-organizations",
      getCurrent: "GET /api/organizations",
      create: "POST /api/organizations/create",
      update: "PATCH /api/organizations",
      delete: "DELETE /api/organizations",
      switchOrg: "POST /api/organizations/switch",
      inviteMember: "POST /api/organizations/members",
      updateMemberRole: "PATCH /api/organizations/members/:memberId",
      removeMember: "DELETE /api/organizations/members/:memberId",
      acceptInvite: "POST /api/organizations/accept-invite",
    },
    webhooks: {
      list: "GET /api/webhooks",
      create: "POST /api/webhooks",
      get: "GET /api/webhooks/:id",
      update: "PUT /api/webhooks/:id",
      delete: "DELETE /api/webhooks/:id",
      deliveries: "GET /api/webhooks/:id/deliveries",
    },
    admin: {
      stats: "GET /api/admin/stats",
      users: "GET /api/admin/users",
      getUser: "GET /api/admin/users/:id",
      updateUser: "PATCH /api/admin/users/:id",
      updateRole: "PATCH /api/admin/users/:id/role",
      suspendUser: "POST /api/admin/users/:id/suspend",
      activateUser: "POST /api/admin/users/:id/activate",
      deleteUser: "DELETE /api/admin/users/:id",
      auditLogs: "GET /api/admin/audit-logs",
      health: "GET /api/admin/health",
    },
  },
};
